<?php
require_once __DIR__.'/../config/auth.php';require_role('owner');$pdo=db();$bid=branch_id();
$q=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN DATE(created_at)=CURDATE() THEN total END),0) today,COALESCE(SUM(CASE WHEN YEAR(created_at)=YEAR(CURDATE()) AND MONTH(created_at)=MONTH(CURDATE()) THEN total END),0) month,COUNT(CASE WHEN DATE(created_at)=CURDATE() THEN 1 END) trx,COALESCE(SUM(CASE WHEN DATE(created_at)=CURDATE() THEN profit END),0) profit FROM transactions WHERE status='paid' AND branch_id=?");$q->execute([$bid]);$stat=$q->fetch();
$q=$pdo->prepare("SELECT COALESCE(SUM(d.quantity),0) FROM transaction_details d JOIN transactions t ON t.id=d.transaction_id WHERE DATE(t.created_at)=CURDATE() AND t.status='paid' AND t.branch_id=?");$q->execute([$bid]);$sold=$q->fetchColumn();
$q=$pdo->prepare('SELECT name,stock,min_stock FROM products WHERE branch_id=? AND is_active=1 AND stock<=min_stock ORDER BY stock LIMIT 6');$q->execute([$bid]);$low=$q->fetchAll();
$q=$pdo->prepare('SELECT t.invoice,t.total,t.created_at,u.name FROM transactions t JOIN users u ON u.id=t.cashier_id WHERE t.branch_id=? ORDER BY t.id DESC LIMIT 8');$q->execute([$bid]);$recent=$q->fetchAll();
$q=$pdo->prepare('SELECT name FROM branches WHERE id=?');$q->execute([$bid]);$branch=$q->fetchColumn()?:'Cabang';$pageTitle='Dasbor '.$branch;$active='dashboard';include __DIR__.'/../includes/header.php';?>
<div class="grid stats"><div class="stat-card"><i class="bi bi-cash-stack"></i><small>Omzet hari ini</small><strong><?=rupiah($stat['today'])?></strong></div><div class="stat-card"><i class="bi bi-calendar3"></i><small>Omzet bulan ini</small><strong><?=rupiah($stat['month'])?></strong></div><div class="stat-card"><i class="bi bi-receipt"></i><small>Transaksi hari ini</small><strong><?=$stat['trx']?></strong></div><div class="stat-card"><i class="bi bi-bag-check"></i><small>Produk terjual</small><strong><?=$sold?></strong></div><div class="stat-card"><i class="bi bi-graph-up"></i><small>Laba kotor</small><strong><?=rupiah($stat['profit'])?></strong></div></div>
<div class="grid two-col"><section class="card"><h2>Transaksi terbaru</h2><div class="table-wrap"><table class="table"><tbody><?php foreach($recent as $r):?><tr><td><strong><?=e($r['invoice'])?></strong><br><small><?=e($r['name'])?></small></td><td><?=rupiah($r['total'])?></td></tr><?php endforeach;?></tbody></table></div></section><section class="card"><h2>Stok hampir habis</h2><div class="table-wrap"><table class="table"><tbody><?php foreach($low as $p):?><tr><td><?=e($p['name'])?></td><td class="low-stock"><?=$p['stock']?> tersisa</td></tr><?php endforeach;?></tbody></table><?php if(!$low):?><div class="empty-state">Stok aman.</div><?php endif;?></div></section></div><?php include __DIR__.'/../includes/footer.php';?>
