<?php
require_once __DIR__.'/../config/auth.php'; require_role('owner'); $pdo=db(); $id=(int)($_GET['id']??0);
$p=['name'=>'','sku'=>'','category_id'=>'','purchase_price'=>0,'selling_price'=>0,'stock'=>0,'min_stock'=>5,'image'=>'','is_active'=>1]; $extras=[];
if($id){$s=$pdo->prepare('SELECT * FROM products WHERE id=? AND branch_id=?');$s->execute([$id,branch_id()]);$p=$s->fetch();if(!$p){http_response_code(404);exit('Produk tidak ditemukan.');}$s=$pdo->prepare('SELECT t.name,t.price,t.purchase_price,t.stock,t.min_stock FROM toppings t JOIN product_toppings pt ON pt.topping_id=t.id WHERE pt.product_id=? AND t.branch_id=? ORDER BY t.name');$s->execute([$id,branch_id()]);$extras=$s->fetchAll();}
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$data=[trim($_POST['name']),trim($_POST['sku']),(int)$_POST['category_id'],(float)$_POST['purchase_price'],(float)$_POST['selling_price'],max(0,(int)$_POST['stock']),max(0,(int)$_POST['min_stock']),isset($_POST['is_active'])?1:0];$image=$p['image'];
 if(!empty($_FILES['image']['name'])){$f=$_FILES['image'];$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);if($f['error']!==UPLOAD_ERR_OK||!isset($allowed[$mime])||$f['size']>2*1024*1024){flash('error','Gambar harus JPG, PNG, atau WebP maksimal 2 MB.');redirect('/owner/produk_form.php'.($id?'?id='.$id:''));}$image=bin2hex(random_bytes(12)).'.'.$allowed[$mime];move_uploaded_file($f['tmp_name'],__DIR__.'/../uploads/products/'.$image);}
 try{$pdo->beginTransaction();$cat=$pdo->prepare('SELECT id FROM categories WHERE id=? AND branch_id=?');$cat->execute([$data[2],branch_id()]);if(!$cat->fetchColumn())throw new RuntimeException('Kategori tidak valid.');if($id){$pdo->prepare('UPDATE products SET name=?,sku=?,category_id=?,purchase_price=?,selling_price=?,stock=?,min_stock=?,is_active=?,image=? WHERE id=? AND branch_id=?')->execute([...$data,$image,$id,branch_id()]);}else{$pdo->prepare('INSERT INTO products(name,sku,category_id,purchase_price,selling_price,stock,min_stock,is_active,image,branch_id) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([...$data,$image,branch_id()]);$id=(int)$pdo->lastInsertId();}$pdo->prepare('DELETE FROM product_toppings WHERE product_id=?')->execute([$id]);$findTop=$pdo->prepare('SELECT id FROM toppings WHERE name=? AND branch_id=?');$insertTop=$pdo->prepare('INSERT INTO toppings(name,price,purchase_price,stock,min_stock,is_available,branch_id) VALUES(?,?,?,?,?,1,?)');$updateTop=$pdo->prepare('UPDATE toppings SET price=?,purchase_price=?,stock=?,min_stock=?,is_available=1 WHERE id=? AND branch_id=?');$link=$pdo->prepare('INSERT IGNORE INTO product_toppings(product_id,topping_id) VALUES(?,?)');foreach($_POST['topping_name']??[] as $i=>$name){$name=trim($name);$price=max(0,(float)($_POST['topping_price'][$i]??0));$cost=max(0,(float)($_POST['topping_cost'][$i]??0));$stock=max(0,(int)($_POST['topping_stock'][$i]??0));$min=max(0,(int)($_POST['topping_min'][$i]??0));if($name==='')continue;$findTop->execute([$name,branch_id()]);$topId=$findTop->fetchColumn();if($topId)$updateTop->execute([$price,$cost,$stock,$min,$topId,branch_id()]);else{$insertTop->execute([$name,$price,$cost,$stock,$min,branch_id()]);$topId=$pdo->lastInsertId();}$link->execute([$id,$topId]);}$pdo->commit();audit_log('product_saved','product',$id,[],['name'=>$data[0],'sku'=>$data[1]]);flash('success','Produk dan pilihan topping berhasil disimpan.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log($e->getMessage());flash('error','Produk gagal disimpan. Periksa SKU, kategori, dan topping.');}
 redirect('/owner/produk.php');
}
$cs=$pdo->prepare('SELECT * FROM categories WHERE branch_id=? ORDER BY name');$cs->execute([branch_id()]);$cats=$cs->fetchAll();$pageTitle=$id?'Edit Produk':'Tambah Produk';$active='produk';include __DIR__.'/../includes/header.php';?>
<section class="card" style="max-width:900px"><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><label>Nama produk<input name="name" value="<?=e($p['name'])?>" required></label><label>SKU<input name="sku" value="<?=e($p['sku'])?>" required></label><label>Kategori<select name="category_id" required><option value="">Pilih kategori</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=$c['id']==$p['category_id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select></label><label>Harga modal<input type="number" name="purchase_price" min="0" value="<?=$p['purchase_price']?>" required></label><label>Harga jual<input type="number" name="selling_price" min="0" value="<?=$p['selling_price']?>" required></label><label>Stok awal/saat ini<input type="number" name="stock" min="0" value="<?=$p['stock']?>" required></label><label>Batas stok minimum<input type="number" name="min_stock" min="0" value="<?=$p['min_stock']?>" required></label><label>Gambar produk<input type="file" name="image" accept="image/jpeg,image/png,image/webp"><small class="muted">JPG, PNG, atau WebP maksimal 2 MB.</small></label><label><span>Status</span><span><input type="checkbox" name="is_active" <?=$p['is_active']?'checked':''?>> Produk aktif</span></label>
<div class="field full topping-editor"><div class="card-head"><div><h2>Pilihan topping</h2><small class="muted">Isi harga jual, modal, stok, dan batas minimum.</small></div><button type="button" class="btn soft sm" id="add-topping"><i class="bi bi-plus-lg"></i> Tambah topping</button></div><div id="topping-rows"><?php foreach($extras as $x):?><div class="topping-edit-row"><input name="topping_name[]" value="<?=e($x['name'])?>" placeholder="Nama" required><input name="topping_price[]" type="number" min="0" value="<?=$x['price']?>" placeholder="Harga jual" required><input name="topping_cost[]" type="number" min="0" value="<?=$x['purchase_price']?>" placeholder="Modal"><input name="topping_stock[]" type="number" min="0" value="<?=$x['stock']?>" placeholder="Stok"><input name="topping_min[]" type="number" min="0" value="<?=$x['min_stock']?>" placeholder="Min."><button type="button" class="icon-btn remove-topping"><i class="bi bi-trash"></i></button></div><?php endforeach;?></div><div id="topping-empty" class="muted" <?=$extras?'hidden':''?>>Belum ada topping.</div></div>
<div class="field full actions"><button class="btn primary">Simpan produk</button><a class="btn soft" href="produk.php">Batal</a></div></form></section>
<script>const rows=document.querySelector('#topping-rows'),empty=document.querySelector('#topping-empty');function sync(){empty.hidden=!!rows.children.length}document.querySelector('#add-topping').onclick=()=>{const row=document.createElement('div');row.className='topping-edit-row';row.innerHTML='<input name="topping_name[]" placeholder="Nama topping" required><input name="topping_price[]" type="number" min="0" placeholder="Harga jual" required><input name="topping_cost[]" type="number" min="0" placeholder="Modal"><input name="topping_stock[]" type="number" min="0" placeholder="Stok"><input name="topping_min[]" type="number" min="0" value="5" placeholder="Min."><button type="button" class="icon-btn remove-topping"><i class="bi bi-trash"></i></button>';rows.append(row);sync()};rows.onclick=e=>{const b=e.target.closest('.remove-topping');if(b){b.closest('.topping-edit-row').remove();sync()}};</script>
<?php include __DIR__.'/../includes/footer.php';?>
