<?php
require_once __DIR__.'/../config/database.php';$pdo=db();
function col(PDO $p,string $t,string $c):bool{$s=$p->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$s->execute([$t,$c]);return(bool)$s->fetchColumn();}
$pdo->exec("CREATE TABLE IF NOT EXISTS invoice_sequences(branch_id INT UNSIGNED NOT NULL,sequence_date DATE NOT NULL,last_number INT UNSIGNED NOT NULL DEFAULT 0,PRIMARY KEY(branch_id,sequence_date)) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE IF NOT EXISTS cash_shifts(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,branch_id INT UNSIGNED NOT NULL,cashier_id INT UNSIGNED NOT NULL,opening_cash DECIMAL(14,2) NOT NULL,closing_cash DECIMAL(14,2) NULL,expected_cash DECIMAL(14,2) NULL,difference DECIMAL(14,2) NULL,status ENUM('open','closed') NOT NULL DEFAULT 'open',opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,closed_at DATETIME NULL,notes VARCHAR(255) NULL,INDEX(branch_id,status),FOREIGN KEY(branch_id) REFERENCES branches(id),FOREIGN KEY(cashier_id) REFERENCES users(id)) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE IF NOT EXISTS audit_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,branch_id INT UNSIGNED NULL,user_id INT UNSIGNED NOT NULL,action VARCHAR(60) NOT NULL,entity VARCHAR(60) NOT NULL,entity_id BIGINT UNSIGNED NULL,before_data JSON NULL,after_data JSON NULL,ip_address VARCHAR(45) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(branch_id,created_at),FOREIGN KEY(branch_id) REFERENCES branches(id),FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB");
foreach(['purchase_price'=>'DECIMAL(14,2) NOT NULL DEFAULT 0','stock'=>'INT NOT NULL DEFAULT 0','min_stock'=>'INT NOT NULL DEFAULT 5'] as $c=>$def)if(!col($pdo,'toppings',$c))$pdo->exec("ALTER TABLE toppings ADD `$c` $def");
if(!col($pdo,'transactions','shift_id'))$pdo->exec('ALTER TABLE transactions ADD shift_id BIGINT UNSIGNED NULL AFTER branch_id, ADD INDEX(shift_id)');
echo "Migrasi operasional selesai.\n";
