<?php require_once __DIR__.'/../config/auth.php'; require_login(); $pageTitle=$pageTitle??'Dasbor'; $active=$active??''; ?>
<!doctype html><html lang="id"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#704326"><title><?=e($pageTitle)?> · <?=APP_NAME?></title><link rel="icon" type="image/png" href="<?=BASE_URL?>/assets/icons/favicon.png">
<link rel="manifest" href="<?=BASE_URL?>/manifest.json"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<link rel="stylesheet" href="<?=BASE_URL?>/assets/css/style.css"><link rel="stylesheet" href="<?=BASE_URL?>/assets/css/branding.css"><link rel="stylesheet" href="<?=BASE_URL?>/assets/css/dashboard.css"><link rel="stylesheet" href="<?=BASE_URL?>/assets/css/extras.css"><link rel="stylesheet" href="<?=BASE_URL?>/assets/css/cart.css"><link rel="stylesheet" href="<?=BASE_URL?>/assets/css/orders.css"><link rel="stylesheet" href="<?=BASE_URL?>/assets/css/notifications.css"><link rel="stylesheet" href="<?=BASE_URL?>/assets/css/ui-feedback.css"></head><body class="<?=e($bodyClass??'')?>">
<?php include __DIR__.'/sidebar.php'; ?><main class="app-main"><header class="topbar"><button class="icon-btn menu-toggle" aria-label="Buka menu"><i class="bi bi-list"></i></button><div><small><?=date('l, d M Y')?></small><h1><?=e($pageTitle)?></h1></div><?php if(user()['role']==='owner'):?><a class="avatar" href="<?=BASE_URL?>/owner/profil.php" aria-label="Profil"><?=strtoupper(substr(user()['name'],0,1))?></a><?php else:?><span class="avatar" aria-label="Akun kasir"><?=strtoupper(substr(user()['name'],0,1))?></span><?php endif;?></header>
<section class="content"><?php if($f=pull_flash()): ?><div class="alert <?=$f['type']?>"><?=e($f['message'])?></div><?php endif; ?>
